pipeline {
    agent any
    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/Yash-Kalekar/TuteDude_DevOps_Assignments.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'pip3 install -r requirements.txt'
            }
        }
        stage('Restart Flask') {
            steps {
                sh 'pm2 restart flask-app || pm2 start app.py --interpreter=python3 --name flask-app'
            }
        }
    }
}
